name: Check Arbitration

on:
  schedule:
    - cron: "*/1 * * * *" # Запуск каждую минуту
  workflow_dispatch: # Для ручного запуска

jobs:
  arbitration-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script to check arbitration
      run: |
        # Команда, которая запускает проверку арбитража
        curl -X POST https://your-domain.com/api/check-arbitration
